server:
  port: 8080

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/jobSeeking"
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        default_schema: public
        format_sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
  mail:
    host: live.smtp.mailtrap.io
    port: 587
    username: api
    password: 34bb364b211bf52780c5e9ed4155b779
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  signerKey: "LHdv9EVi3BKZeBHVBzqPE35+0PzgIPPlEkDa+8WSugOj+QAXKDO3DfjPDhSYmkjN"
main:
    allow-circular-references: true